name: Auto Merge

on:
  push:
    branches:
      - '**'
env:
  NODE_VERSION: '16.x'
  GITHUB_NAME: ${{ github.event.head_commit.author.name }}
  GITHUB_EMAIL: ${{ github.event.head_commit.author.email }}

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - run: echo name ${{ env.GITHUB_NAME }}
      - run: echo email ${{ env.GITHUB_EMAIL }}
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: actions/checkout@v2

      - name: CI
        run: npm ci
