name: Auto Merge

on:
  workflow_run:
    workflows: ['CD']
    types:
      - completed

env:
  NODE_VERSION: '16.x'
  GITHUB_NAME: ${{ github.event.head_commit.author.name }}
  GITHUB_EMAIL: ${{ github.event.head_commit.author.email }}

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
      - run: echo checkout branch success
