name: Auto Merge

on:
  push:
    branches:
      - '**'
env:
  NODE_VERSION: '16.x'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{ toJson(github) }}
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: actions/checkout@v2

      - name: CI
        run: npm ci
