name: canary-publish

on:
  push:
    branches:    
      - 'feature/**'
env:
  NODE_VERSION: '16.x'
  NPM_REGISTRY_URL: 'https://registry.npmjs.org'
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}      

jobs:
  canary:
    if: "!contains(github.event.head_commit.message, 'skip canary')"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.NPM_REGISTRY_URL }}
        
      - run: npm ci

      - name: canary deploy
        run: npm run deploy:canary




