name: CD

on:
  push:
    branches:
      - 'main'

env:
  NODE_VERSION: '16.x'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm ci

      - name: build
        run: npm run build:all
